name: coffie_ecom
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  fbloc_event_gen: ^3.2.6+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  injectable: ^2.5.0
  intl: 0.19.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
